// Generated by Wrangler by running `wrangler types`

interface Env {
	EMAILS: KVNamespace;
	EVENTS: KVNamespace;
	SITE_URL: "https://alonmashmaut.org";
	API_URL: "https://api.alonmashmaut.org" | "https://mashmaut-api-staging.alonmashmaut.workers.dev";
	SITE_NAME: "משמעות" | "משמעות (staging)";
	ADMIN_EMAIL: "alonmashmaut@gmail.com";
	FROM_EMAIL: "alon@alonmashmaut.org" | "onboarding@resend.dev";
	FROM_NAME: "עלון משמעות" | "משמעות staging";
	GITHUB_REPO: "tuvyanoam-code/mashmaut";
	GITHUB_BRANCH: "main" | "staging";
	STAGING_MODE: "1";
	RESEND_API_KEY: string;
	ADMIN_API_KEY: string;
}
